import globals from 'globals';

/**
 * S4 Ledger — ESLint Flat Config
 * Enforces code quality across prod-app and demo-app source files.
 * Uses flat config (eslint.config.js) for ESLint 9+.
 */
export default [
  {
    // Global ignores
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/*.min.js',
      '**/s4-assets/**',
      '**/__pycache__/**',
    ],
  },
  {
    // JavaScript source files
    files: ['prod-app/src/js/**/*.js', 'demo-app/src/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        // Chart.js global
        Chart: 'readonly',
        // Bootstrap global
        bootstrap: 'readonly',
        // CDN libraries
        XLSX: 'readonly',
        pdfjsLib: 'readonly',
        mammoth: 'readonly',
        QRCode: 'readonly',
        // Supabase
        supabase: 'readonly',
        // S4 namespace and cross-module globals
        S4: 'writable',
        S4Store: 'readonly',
        S4_PLATFORMS: 'readonly',
        S4_DEFENSE_DOCS: 'readonly',
        S4_buildProgramOptions: 'readonly',
        S4_countPlatforms: 'readonly',
        S4_getComponents: 'readonly',
        S4_getReadiness: 'readonly',
        DOC_BRANCHES: 'readonly',
        DOC_CATEGORIES: 'readonly',
        // Cross-module functions (defined in one file, used in others)
        _showNotif: 'readonly',
        _anchorToXRPL: 'readonly',
        _bpRenderInPanel: 'readonly',
        _currentILSTool: 'writable',
        _currentRole: 'writable',
        _currentSection: 'writable',
        _currentTitle: 'writable',
        _currentUser: 'writable',
        _customVisibleTabs: 'writable',
        _demoMode: 'writable',
        _demoSession: 'writable',
        _getSelectedVaultHashes: 'readonly',
        _initDemoSession: 'readonly',
        _lastUploadedFileHash: 'writable',
        _lastUploadedFileName: 'writable',
        _lastUploadedFileSize: 'writable',
        _onboardTier: 'writable',
        _onboardTiers: 'readonly',
        _riskCache: 'writable',
        _s4PatchChartTheme: 'readonly',
        _s4RefreshCharts: 'readonly',
        _s4ReleaseFocusTrap: 'readonly',
        _s4Roles: 'readonly',
        _s4TrapFocus: 'readonly',
        _updateDemoSlsBalance: 'readonly',
        _updateSlsBalance: 'readonly',
        _vaultKey: 'writable',
        _allHubTabs: 'readonly',
        addAiMessage: 'readonly',
        addToVault: 'readonly',
        applyTabVisibility: 'readonly',
        calcCompliance: 'readonly',
        calcLifecycle: 'readonly',
        calcROI: 'readonly',
        closeOnboarding: 'readonly',
        closeWalletSidebar: 'readonly',
        currentHubPanel: 'writable',
        dmsmsItems: 'writable',
        exportVault: 'readonly',
        generateILSReport: 'readonly',
        generateLifecycleActions: 'readonly',
        getLocalRecords: 'readonly',
        getPartsDB: 'readonly',
        hideAnchorAnimation: 'readonly',
        ilsResults: 'writable',
        initILSChecklist: 'readonly',
        injectChartContainers: 'readonly',
        loadDMSMSData: 'readonly',
        loadDashboardStats: 'readonly',
        loadPerformanceMetrics: 'readonly',
        loadPredictiveData: 'readonly',
        loadReadinessData: 'readonly',
        loadReportPreview: 'readonly',
        loadRiskData: 'readonly',
        loadSBOMData: 'readonly',
        loadSubmissionHistory: 'readonly',
        loadWalletData: 'readonly',
        navigateTo: 'readonly',
        openILSTool: 'readonly',
        parseXMLContent: 'readonly',
        persistILSUpload: 'readonly',
        populateDigitalThreadDropdown: 'readonly',
        reloadVaultForRole: 'readonly',
        renderActionCalendar: 'readonly',
        renderComplianceCharts: 'readonly',
        renderDMSMSCharts: 'readonly',
        renderDocLibrary: 'readonly',
        renderHubActions: 'readonly',
        renderPartsResults: 'readonly',
        renderROICharts: 'readonly',
        renderReadinessCharts: 'readonly',
        renderRiskCharts: 'readonly',
        renderVault: 'readonly',
        riskItems: 'writable',
        runAutoAnalysisOnUpload: 'readonly',
        s4ActionItems: 'writable',
        s4Analytics: 'writable',
        s4CDRLValidator: 'writable',
        s4ContractExtractor: 'writable',
        s4DocLibrary: 'writable',
        s4GFPTracker: 'writable',
        s4Notify: 'readonly',
        s4Provenance: 'writable',
        s4Team: 'writable',
        s4Vault: 'writable',
        saveLocalRecord: 'readonly',
        saveStats: 'readonly',
        sessionId: 'writable',
        sessionRecords: 'writable',
        sha256: 'readonly',
        sha256Binary: 'readonly',
        showAddActionModal: 'readonly',
        showAnchorAnimation: 'readonly',
        showILSResults: 'readonly',
        showOnboarding: 'readonly',
        showRoleSelector: 'readonly',
        showSampleDigitalThread: 'readonly',
        showSavedAnalyses: 'readonly',
        showSection: 'readonly',
        showWebhookSettings: 'readonly',
        showWorkspaceNotification: 'readonly',
        stats: 'writable',
        switchHubTab: 'readonly',
        toggleGlobalSearch: 'readonly',
        toggleNotifHistory: 'readonly',
        toggleShortcuts: 'readonly',
        updateAiContext: 'readonly',
        updateStats: 'readonly',
        updateTxLog: 'readonly',
        uploadedDocumentStore: 'writable',
      },
    },
    rules: {
      // Error prevention
      'no-undef': 'warn',
      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
      'no-redeclare': 'warn',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-unreachable': 'warn',
      'no-constant-condition': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-extra-semi': 'error',
      'no-func-assign': 'warn', // failsafe inline scripts intentionally reassign module functions
      'no-inner-declarations': 'warn',

      // Best practices
      'eqeqeq': ['warn', 'smart'],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'warn',
      'no-with': 'error',
      'no-throw-literal': 'warn',
      'prefer-const': 'off', // many vars use var intentionally

      // Style (relaxed — large existing codebase)
      'no-trailing-spaces': 'off',
      'semi': 'off',
      'quotes': 'off',
      'indent': 'off',
      'comma-dangle': 'off',
    },
  },
  {
    // Test files — more relaxed
    files: ['tests/**/*.js', '**/*.test.js', '**/*.spec.js'],
    languageOptions: {
      globals: {
        ...globals.node,
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly',
        test: 'readonly',
      },
    },
    rules: {
      'no-undef': 'off',
      'no-unused-vars': 'off',
    },
  },
];
