// ═══════════════════════════════════════════════════════════════════
// S4 Ledger — Defense Document Reference Library
// Real MIL-STDs, OPNAVINSTs, Defense Federal Acquisition Regulations,
// and governing documents organized by category and branch
// ═══════════════════════════════════════════════════════════════════

const S4_DEFENSE_DOCS = [

// ══════════════ MIL-STD — Military Standards ══════════════
{ id:'MIL-STD-1388-1A', title:'Logistics Support Analysis', category:'ILS', branch:'JOINT', description:'Establishes requirements for Logistics Support Analysis (LSA) to influence design and identify support requirements.', url:'https://quicksearch.dla.mil/qsDocDetails.aspx?ident_number=36026', keywords:'LSA logistics support analysis design influence maintenance supportability' },
{ id:'MIL-STD-1388-2B', title:'LSA Record — Data Element Definitions', category:'ILS', branch:'JOINT', description:'Defines data elements for the Logistics Support Analysis Record (LSAR) database.', url:'https://quicksearch.dla.mil/qsDocDetails.aspx?ident_number=36027', keywords:'LSAR data elements database record logistics' },
{ id:'MIL-STD-1390D', title:'Level of Repair Analysis', category:'Readiness', branch:'JOINT', description:'Provides standard for performing level of repair analysis (LORA) to determine optimal maintenance level.', url:'https://quicksearch.dla.mil/', keywords:'LORA level repair analysis maintenance depot intermediate organizational' },
{ id:'MIL-STD-1629A', title:'FMECA — Failure Mode Effects and Criticality Analysis', category:'Readiness', branch:'JOINT', description:'Procedures for performing failure mode, effects, and criticality analysis on systems and equipment.', url:'https://quicksearch.dla.mil/', keywords:'FMECA failure mode effects criticality analysis reliability' },
{ id:'MIL-STD-882E', title:'System Safety', category:'Safety', branch:'JOINT', description:'Standard practice for system safety across the system lifecycle, including risk assessment and hazard analysis.', url:'https://quicksearch.dla.mil/', keywords:'system safety hazard analysis risk assessment lifecycle mishap' },
{ id:'MIL-STD-881F', title:'Work Breakdown Structure for Defense Materiel Items', category:'Program Mgmt', branch:'JOINT', description:'Defines standard WBS elements for defense acquisition programs.', url:'https://quicksearch.dla.mil/', keywords:'WBS work breakdown structure acquisition program management' },
{ id:'MIL-STD-31000B', title:'Technical Data Packages', category:'Technical Data', branch:'JOINT', description:'Standard for the preparation and delivery of Technical Data Packages (TDP).', url:'https://quicksearch.dla.mil/', keywords:'TDP technical data package engineering drawings specifications' },
{ id:'MIL-STD-130N', title:'Identification Marking of U.S. Military Property', category:'Supply', branch:'JOINT', description:'Requirements for identification marking including UID (Unique Identification) and IUID marking.', url:'https://quicksearch.dla.mil/', keywords:'UID IUID marking identification military property item unique' },
{ id:'MIL-STD-129R', title:'Military Marking for Shipment and Storage', category:'Supply', branch:'JOINT', description:'Marking standards for military shipment, packaging, and storage containers.', url:'https://quicksearch.dla.mil/', keywords:'marking shipment storage container packaging logistics' },
{ id:'MIL-STD-2073-1E', title:'Standard Practice for Military Packaging', category:'Supply', branch:'JOINT', description:'Standard practices for preservation, packing, and packaging of military materiel.', url:'https://quicksearch.dla.mil/', keywords:'packaging preservation packing military materiel' },
{ id:'MIL-STD-810H', title:'Environmental Engineering Considerations and Laboratory Tests', category:'Testing', branch:'JOINT', description:'Test methods and engineering guidance for environmental testing of military equipment (temperature, vibration, humidity, etc.).', url:'https://quicksearch.dla.mil/', keywords:'environmental testing vibration temperature humidity shock' },
{ id:'MIL-STD-461G', title:'EMI/EMC Requirements for Equipment', category:'Testing', branch:'JOINT', description:'Requirements for electromagnetic interference/compatibility testing of military equipment.', url:'https://quicksearch.dla.mil/', keywords:'EMI EMC electromagnetic interference compatibility testing' },
{ id:'MIL-STD-1472H', title:'Human Engineering', category:'Safety', branch:'JOINT', description:'Human factors engineering criteria for design of military systems, equipment, and facilities.', url:'https://quicksearch.dla.mil/', keywords:'human factors engineering ergonomics design criteria' },
{ id:'MIL-STD-1916', title:'DOD Test Method Standard for Acceptance Sampling', category:'Quality', branch:'JOINT', description:'Statistical sampling procedures for acceptance or rejection of lot production.', url:'https://quicksearch.dla.mil/', keywords:'acceptance sampling statistical quality inspection lot' },
{ id:'MIL-STD-2549B', title:'Configuration Management Data Interface', category:'Configuration', branch:'JOINT', description:'Standard for electronic exchange of configuration management data.', url:'https://quicksearch.dla.mil/', keywords:'configuration management data interface electronic exchange' },
{ id:'MIL-STD-3034', title:'Reliability-Centered Maintenance (RCM)', category:'Readiness', branch:'JOINT', description:'Requirements for implementing reliability-centered maintenance for military systems.', url:'https://quicksearch.dla.mil/', keywords:'RCM reliability centered maintenance analysis' },
{ id:'MIL-STD-1798C', title:'Mechanical Equipment and Subsystems Integrity Program', category:'Readiness', branch:'JOINT', description:'Structural integrity requirements for mechanical systems and subsystems.', url:'https://quicksearch.dla.mil/', keywords:'MECSIP mechanical integrity structural subsystem' },

// ══════════════ MIL-HDBK — Military Handbooks ══════════════
{ id:'MIL-HDBK-217F', title:'Reliability Prediction of Electronic Equipment', category:'Readiness', branch:'JOINT', description:'Methods for predicting reliability (MTBF) of electronic equipment.', url:'https://quicksearch.dla.mil/', keywords:'reliability prediction MTBF electronic equipment failure rate' },
{ id:'MIL-HDBK-338B', title:'Electronic Reliability Design Handbook', category:'Readiness', branch:'JOINT', description:'Comprehensive guide for reliability engineering including RAM analysis, testing, and growth.', url:'https://quicksearch.dla.mil/', keywords:'reliability engineering RAM analysis testing growth design' },
{ id:'MIL-HDBK-502', title:'Product Support Analysis', category:'ILS', branch:'JOINT', description:'Handbook for performing product support analysis incorporating all ILS elements.', url:'https://quicksearch.dla.mil/', keywords:'PSA product support analysis ILS elements' },
{ id:'MIL-HDBK-472', title:'Maintainability Prediction', category:'Readiness', branch:'JOINT', description:'Methods for predicting maintainability metrics including MTTR and maintenance man-hours.', url:'https://quicksearch.dla.mil/', keywords:'maintainability prediction MTTR maintenance man-hours' },
{ id:'MIL-HDBK-781A', title:'Reliability Test Methods, Plans, and Environments', category:'Readiness', branch:'JOINT', description:'Handbook of reliability testing methods for military hardware qualification.', url:'https://quicksearch.dla.mil/', keywords:'reliability testing qualification methods plans hardware' },
{ id:'MIL-HDBK-1823A', title:'Non-Destructive Testing Methods', category:'Testing', branch:'JOINT', description:'Comprehensive guide to non-destructive testing/evaluation methods for military equipment.', url:'https://quicksearch.dla.mil/', keywords:'NDT NDE non-destructive testing evaluation inspection' },
{ id:'MIL-HDBK-263B', title:'Electrostatic Discharge Control Handbook', category:'Safety', branch:'JOINT', description:'Guidance on controlling electrostatic discharge (ESD) in handling electronic equipment.', url:'https://quicksearch.dla.mil/', keywords:'ESD electrostatic discharge control handler electronics' },

// ══════════════ OPNAVINST — Navy Instructions ══════════════
{ id:'OPNAVINST 4790.4F', title:'Ships Maintenance and Material Management (3-M)', category:'Maintenance', branch:'USN', description:'Governs the Navy 3-M system for planned maintenance, corrective maintenance, material condition documentation, and work candidate development.', url:'https://www.secnav.navy.mil/', keywords:'3-M maintenance material management PMS MRC CSMP ships' },
{ id:'OPNAVINST 4441.12G', title:'Policies for Afloat Supply Procedures', category:'Supply', branch:'USN', description:'Governs Navy afloat supply procedures including requisitioning, receipt, stowage, issue, and inventory management.', url:'https://www.secnav.navy.mil/', keywords:'afloat supply requisitioning inventory stowage receipt issue COSAL' },
{ id:'OPNAVINST 4790.2J', title:'NAMP — Naval Aviation Maintenance Program', category:'Maintenance', branch:'USN', description:'Master Standard for all naval aviation maintenance policies, procedures, and responsibilities.', url:'https://www.secnav.navy.mil/', keywords:'NAMP aviation maintenance naval aircraft repair depot intermediate' },
{ id:'OPNAVINST 5100.23H', title:'Navy Safety and Occupational Health Program', category:'Safety', branch:'USN', description:'Establishes Navy safety program including mishap reporting, risk management, and safety training.', url:'https://www.secnav.navy.mil/', keywords:'safety occupational health mishap risk management training' },
{ id:'OPNAVINST 3000.12B', title:'Navy Operational Risk Management', category:'Safety', branch:'USN', description:'Provides policy for operational risk management (ORM) integration into all Navy operations.', url:'https://www.secnav.navy.mil/', keywords:'ORM operational risk management deliberate time-critical' },
{ id:'OPNAVINST 4614.1H', title:'Weight Handling Program', category:'Safety', branch:'USN', description:'Navy crane and weight handling program for shore and afloat crane operations.', url:'https://www.secnav.navy.mil/', keywords:'crane weight handling shore afloat inspection testing' },
{ id:'OPNAVINST 5239.1D', title:'Navy Information Assurance', category:'Cybersecurity', branch:'USN', description:'Policy for Navy cybersecurity and information assurance across all networks and systems.', url:'https://www.secnav.navy.mil/', keywords:'cybersecurity information assurance IA NMCI network' },
{ id:'OPNAVINST 4700.7L', title:'Maintenance Policy for Navy Ships', category:'Maintenance', branch:'USN', description:'Establishes policy for depot-level maintenance planning and execution for Navy ships.', url:'https://www.secnav.navy.mil/', keywords:'ship maintenance depot NAVSEA availability overhaul planning' },
{ id:'OPNAVINST 5510.1J', title:'Department of the Navy Information Security Program', category:'Security', branch:'USN', description:'Policy for classified information security including handling, storage, destruction, and transmission.', url:'https://www.secnav.navy.mil/', keywords:'classified information security CUI NOFORN handling storage' },

// ══════════════ COMDTINST — Coast Guard Instructions ══════════════
// ══════════════ DoD Directives & Instructions ══════════════
{ id:'DoDD 5000.01', title:'The Defense Acquisition System', category:'Acquisition', branch:'JOINT', description:'Top-level policy for the management of DoD acquisition programs.', url:'https://www.esd.whs.mil/Directives/', keywords:'acquisition program management ACAT milestone defense' },
{ id:'DoDI 5000.02', title:'Operation of the Adaptive Acquisition Framework', category:'Acquisition', branch:'JOINT', description:'Implements the Adaptive Acquisition Framework (AAF) with six acquisition pathways.', url:'https://www.esd.whs.mil/Directives/', keywords:'AAF adaptive acquisition framework pathway MCA urgent MDAP' },
{ id:'DoD 5000.73', title:'Cost Analysis Guidance and Procedures', category:'Cost Analysis', branch:'JOINT', description:'Policy for cost estimates, LCCE (Life Cycle Cost Estimates), and should-cost analysis.', url:'https://www.esd.whs.mil/Directives/', keywords:'LCCE life cycle cost estimate should-cost analysis CBA' },
{ id:'DoDD 4140.01', title:'Supply Chain Materiel Management Policy', category:'Supply', branch:'JOINT', description:'Top-level policy for DoD supply chain materiel management including inventory and distribution.', url:'https://www.esd.whs.mil/Directives/', keywords:'supply chain materiel management inventory distribution' },
{ id:'DoDI 4140.67', title:'DoD Counterfeit Prevention Policy', category:'Supply', branch:'JOINT', description:'Policy to detect, prevent, and mitigate counterfeit materiel in the DoD supply chain.', url:'https://www.esd.whs.mil/Directives/', keywords:'counterfeit prevention detection mitigation supply chain GIDEP' },
{ id:'DoDI 4151.22', title:'Condition Based Maintenance Plus (CBM+)', category:'Maintenance', branch:'JOINT', description:'Policy for implementing CBM+ to optimize maintenance through condition monitoring and predictive analytics.', url:'https://www.esd.whs.mil/Directives/', keywords:'CBM+ condition based maintenance predictive analytics monitoring' },
{ id:'DoDI 4140.61', title:'Customer Wait Time and Time Definite Delivery', category:'Supply', branch:'JOINT', description:'Standards for supply chain responsiveness including CWT metrics.', url:'https://www.esd.whs.mil/Directives/', keywords:'CWT customer wait time delivery supply responsiveness' },
{ id:'DoDM 4140.27-M', title:'Shelf-Life Management Manual', category:'Supply', branch:'JOINT', description:'Procedures for managing shelf-life of materiel by type and category.', url:'https://www.esd.whs.mil/Directives/', keywords:'shelf-life management materiel storage expiration date' },
{ id:'DoDI 5000.88', title:'Engineering of Defense Systems', category:'Engineering', branch:'JOINT', description:'Policy for systems engineering in defense acquisition.', url:'https://www.esd.whs.mil/Directives/', keywords:'systems engineering SE defense acquisition technical review' },
{ id:'DoDI 5000.90', title:'Cybersecurity for Acquisition Decision Authorities', category:'Cybersecurity', branch:'JOINT', description:'Integrates cybersecurity into acquisition decision-making.', url:'https://www.esd.whs.mil/Directives/', keywords:'cybersecurity acquisition RMF ATO authorization' },

// ══════════════ NAVSEA / NAVAIR / NAVSUP ══════════════
{ id:'NAVSEA S9086-AA-STM-010', title:'NSTM Chapter 001 — General', category:'Maintenance', branch:'USN', description:'Naval Ships Technical Manual — general engineering standards and procedures for ship maintenance.', url:'https://www.navsea.navy.mil/', keywords:'NSTM naval ships technical manual engineering maintenance' },
{ id:'NAVSEA S9086-GY-STM-020', title:'NSTM Chapter 077 — Personnel Protection Equipment', category:'Safety', branch:'USN', description:'Requirements for personnel protection equipment on Navy vessels.', url:'https://www.navsea.navy.mil/', keywords:'PPE personnel protection equipment safety naval' },
{ id:'NAVSEA S9086-CL-STM-010', title:'NSTM Chapter 074 — Welding and Brazing', category:'Maintenance', branch:'USN', description:'Standards and procedures for welding and brazing on Navy ships.', url:'https://www.navsea.navy.mil/', keywords:'welding brazing procedures standards naval ships' },
{ id:'NAVSEA OP 5 Vol. 1', title:'Ammunition and Explosives Safety Ashore', category:'Ordnance', branch:'USN', description:'Comprehensive safety requirements for ammunition and explosives at shore installations.', url:'https://www.navsea.navy.mil/', keywords:'ammunition explosives safety ashore storage handling ordnance' },
{ id:'NAVAIR 00-25-100', title:'Naval Air Systems Command Tech Pub Program', category:'Technical Data', branch:'USN', description:'Governs content and format of NAVAIR technical publications.', url:'https://www.navair.navy.mil/', keywords:'technical publication manual NAVAIR format content' },
{ id:'NAVSUP P-485', title:'Naval Supply Procedures — Afloat Supply', category:'Supply', branch:'USN', description:'Detailed procedures for afloat supply management including COSAL, receipt, expenditure, and inventory.', url:'https://www.navsup.navy.mil/', keywords:'afloat supply COSAL inventory receipt expenditure stowage' },
{ id:'NAVSUP P-723', title:'Navy Supply Financial Management', category:'Supply', branch:'USN', description:'Financial management procedures for Navy supply activities.', url:'https://www.navsup.navy.mil/', keywords:'supply financial management budget obligation expenditure' },

// ══════════════ DFARS / FAR — Acquisition Regulations ══════════════
{ id:'FAR Part 46', title:'Quality Assurance', category:'Quality', branch:'JOINT', description:'Federal Acquisition Regulation part governing quality assurance including warranties (46.7).', url:'https://www.acquisition.gov/far/part-46', keywords:'quality assurance inspection acceptance warranty FAR' },
{ id:'FAR Part 45', title:'Government Property', category:'Supply', branch:'JOINT', description:'Policy for contractor management of government-furnished property (GFP/GFE/GFM).', url:'https://www.acquisition.gov/far/part-45', keywords:'GFP GFE GFM government furnished property equipment material' },
{ id:'FAR Part 42', title:'Contract Administration and Audit Services', category:'Acquisition', branch:'JOINT', description:'Contract administration procedures including DCMA oversight.', url:'https://www.acquisition.gov/far/part-42', keywords:'contract administration DCMA audit oversight management' },
{ id:'DFARS 252.211-7003', title:'Item Unique Identification (IUID)', category:'Supply', branch:'JOINT', description:'DFARS clause requiring UID marking on government property.', url:'https://www.acquisition.gov/dfars', keywords:'IUID UID unique identification marking DoD property tracking' },
{ id:'DFARS 252.246-7007', title:'Contractor Counterfeit Electronic Part Detection', category:'Quality', branch:'JOINT', description:'Requires contractors to implement counterfeit part detection and avoidance systems.', url:'https://www.acquisition.gov/dfars', keywords:'counterfeit detection electronic part avoidance GIDEP ERAI' },
{ id:'DFARS 252.204-7012', title:'Safeguarding Covered Defense Information (CDI)', category:'Cybersecurity', branch:'JOINT', description:'Requires contractors to implement NIST SP 800-171 for protecting CUI.', url:'https://www.acquisition.gov/dfars', keywords:'CUI CDI NIST 800-171 cybersecurity safeguarding covered defense' },

// ══════════════ NIST — Cybersecurity & Compliance ══════════════
{ id:'NIST SP 800-171 Rev. 2', title:'Protecting CUI in Nonfederal Systems', category:'Cybersecurity', branch:'JOINT', description:'Security requirements for protecting Controlled Unclassified Information (CUI) — basis for CMMC.', url:'https://csrc.nist.gov/publications/detail/sp/800-171/rev-2/final', keywords:'CUI CMMC cybersecurity controls access control audit accountability' },
{ id:'NIST SP 800-53 Rev. 5', title:'Security and Privacy Controls for Information Systems', category:'Cybersecurity', branch:'JOINT', description:'Comprehensive catalog of security and privacy controls for federal information systems.', url:'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final', keywords:'security controls privacy federal information system FedRAMP' },
{ id:'NIST SP 800-37 Rev. 2', title:'Risk Management Framework (RMF)', category:'Cybersecurity', branch:'JOINT', description:'Framework for applying risk management to information systems including authorization.', url:'https://csrc.nist.gov/publications/detail/sp/800-37/rev-2/final', keywords:'RMF risk management framework ATO authorization assessment' },
{ id:'NIST SP 800-82 Rev. 3', title:'Guide to OT Security', category:'Cybersecurity', branch:'JOINT', description:'Security guidance for Operational Technology (OT) including SCADA and industrial control systems.', url:'https://csrc.nist.gov/publications/detail/sp/800-82/rev-3/final', keywords:'OT operational technology SCADA ICS industrial control security' },
{ id:'CMMC Model v2.0', title:'Cybersecurity Maturity Model Certification', category:'Cybersecurity', branch:'JOINT', description:'Three-level certification model for defense contractor cybersecurity — required for CUI handling.', url:'https://dodcio.defense.gov/CMMC/', keywords:'CMMC certification maturity model Level 1 Level 2 Level 3 assessment' },
// ══════════════ DMSMS-Specific ══════════════
{ id:'SD-22', title:'DMSMS Program Manager Guidebook', category:'DMSMS', branch:'JOINT', description:'Comprehensive guide for establishing and managing DMSMS programs including case resolution.', url:'https://www.dau.edu/', keywords:'DMSMS program manager guidebook obsolescence case resolution' },
{ id:'SD-19', title:'Parts Management Guide', category:'DMSMS', branch:'JOINT', description:'DoD guide for parts selection, management, and standardization to reduce obsolescence risk.', url:'https://www.dau.edu/', keywords:'parts management standardization selection obsolescence reduction' },
{ id:'GIDEP Handbook', title:'Government-Industry Data Exchange Program', category:'DMSMS', branch:'JOINT', description:'Procedures for participating in GIDEP for alerts on failures, problematic parts, and DMSMS notices.', url:'https://www.gidep.org/', keywords:'GIDEP data exchange alerts failures diminishing sources notifications' },
{ id:'DoDI 4245.15', title:'DMSMS Management Policy', category:'DMSMS', branch:'JOINT', description:'DoD instruction establishing policy and responsibilities for DMSMS management.', url:'https://www.esd.whs.mil/Directives/', keywords:'DMSMS management policy obsolescence diminishing manufacturing' },

// ══════════════ Configuration Management ══════════════
{ id:'MIL-HDBK-61A', title:'Configuration Management Guidance', category:'Configuration', branch:'JOINT', description:'Handbook for implementing configuration management including identification, control, status accounting, and audit.', url:'https://quicksearch.dla.mil/', keywords:'configuration management CM identification control status accounting audit' },
{ id:'EIA-649-1', title:'Configuration Management Requirements', category:'Configuration', branch:'JOINT', description:'Industry standard (adopted by DoD) for CM principles and requirements.', url:'https://www.sae.org/', keywords:'EIA-649 configuration management requirements industry standard' },
{ id:'ANSI/EIA-632', title:'Processes for Engineering a System', category:'Engineering', branch:'JOINT', description:'Standard defining systems engineering processes applicable to defense programs.', url:'https://www.sae.org/', keywords:'systems engineering processes requirements analysis design' },
// ══════════════ Packaging, Handling, Storage, Transportation ══════════════
{ id:'ASTM D3951', title:'Commercial Packaging Standard', category:'Supply', branch:'JOINT', description:'Standard practice for commercial packaging of supplies and equipment.', url:'https://www.astm.org/', keywords:'commercial packaging standard supplies equipment' },
{ id:'MIL-STD-1366E', title:'Transportability Criteria', category:'Supply', branch:'JOINT', description:'Design criteria for military equipment transportability by air, land, and sea.', url:'https://quicksearch.dla.mil/', keywords:'transportability design criteria air land sea military' },
{ id:'DTR 4500.9-R', title:'Defense Transportation Regulation', category:'Supply', branch:'JOINT', description:'Policy and procedures for DoD transportation and traffic management.', url:'https://www.ustranscom.mil/dtr/', keywords:'DTR transportation traffic management shipment movement' },

// ══════════════ Technical Publications ══════════════
{ id:'MIL-STD-40051-1', title:'Preparation of Digital Technical Information', category:'Technical Data', branch:'JOINT', description:'Standard for preparing interactive electronic technical manuals (IETMs).', url:'https://quicksearch.dla.mil/', keywords:'IETM interactive electronic technical manual digital' },
{ id:'MIL-STD-38784B', title:'Standard Practice for Technical Manuals', category:'Technical Data', branch:'JOINT', description:'Standard practices for content and format of military technical manuals.', url:'https://quicksearch.dla.mil/', keywords:'technical manual format content standard practice' },
{ id:'S1000D', title:'International Specification for Technical Publications', category:'Technical Data', branch:'JOINT', description:'International standard for producing technical publications using a Common Source Database (CSDB).', url:'https://www.s1000d.org/', keywords:'S1000D technical publications CSDB data module international' },

// ══════════════ Contract Data Requirements List ══════════════
{ id:'DI-ILSS-80899A', title:'DI for Provisioning Technical Documentation', category:'ILS', branch:'JOINT', description:'Data item description for provisioning documentation delivered under contract.', url:'https://quicksearch.dla.mil/', keywords:'DI data item provisioning technical documentation contract' },
{ id:'DI-SESS-81495C', title:'DI for Reliability Analysis Report', category:'Readiness', branch:'JOINT', description:'Data item description for reliability reports and RAM analysis deliverables.', url:'https://quicksearch.dla.mil/', keywords:'reliability analysis report RAM data item deliverable' },
{ id:'DI-MGMT-80368A', title:'DI for CDRL Contract Data Requirements', category:'Acquisition', branch:'JOINT', description:'Standard data item for contract data requirements lists (CDRLs).', url:'https://quicksearch.dla.mil/', keywords:'CDRL contract data requirements list deliverable schedule' },

// ══════════════ ILS Elements — Key References ══════════════
{ id:'DAG CH 4-3.7', title:'Provisioning (ILS Element)', category:'ILS', branch:'JOINT', description:'Defense Acquisition Guidebook coverage of provisioning including initial spares, range and depth analysis.', url:'https://www.dau.edu/acquipedia', keywords:'provisioning initial spares range depth analysis ILS element' },
{ id:'DAG CH 4-3.5', title:'Supply Support (ILS Element)', category:'ILS', branch:'JOINT', description:'DAG guidance on supply support planning including demand analysis, cataloging, and distribution.', url:'https://www.dau.edu/acquipedia', keywords:'supply support demand analysis cataloging distribution ILS element' },
{ id:'DAG CH 4-3.4', title:'Maintenance Planning (ILS Element)', category:'ILS', branch:'JOINT', description:'DAG guidance on maintenance concept development, LORA, and maintenance task analysis.', url:'https://www.dau.edu/acquipedia', keywords:'maintenance planning concept LORA task analysis ILS element' },
{ id:'DAG CH 4-3.3', title:'Manpower & Personnel (ILS Element)', category:'ILS', branch:'JOINT', description:'DAG guidance on manpower requirements, personnel skills, and training needs analysis.', url:'https://www.dau.edu/acquipedia', keywords:'manpower personnel training skills requirements ILS element' },
{ id:'DAG CH 4-3.6', title:'Technical Data (ILS Element)', category:'ILS', branch:'JOINT', description:'DAG guidance on technical data packages, manuals, and information management.', url:'https://www.dau.edu/acquipedia', keywords:'technical data TDP manuals information management ILS element' },
{ id:'DAG CH 4-3.8', title:'Support Equipment (ILS Element)', category:'ILS', branch:'JOINT', description:'DAG guidance on common and peculiar support equipment requirements.', url:'https://www.dau.edu/acquipedia', keywords:'support equipment SE TMDE PGSE common peculiar ILS element' },
{ id:'DAG CH 4-3.10', title:'Packaging Handling Storage Transportation (ILS Element)', category:'ILS', branch:'JOINT', description:'DAG guidance on PHS&T requirements for military systems.', url:'https://www.dau.edu/acquipedia', keywords:'PHS&T packaging handling storage transportation ILS element' },
];

// Category metadata for display
const DOC_CATEGORIES = {
    'ILS':           { icon:'fa-cubes',         color:'#00aaff', label:'Integrated Logistics Support' },
    'Readiness':     { icon:'fa-heartbeat',      color:'#00aaff', label:'Readiness & Reliability' },
    'Maintenance':   { icon:'fa-wrench',         color:'#00aaff', label:'Maintenance' },
    'Supply':        { icon:'fa-boxes-stacked',  color:'#00aaff', label:'Supply Chain & Materiel' },
    'DMSMS':         { icon:'fa-exclamation-triangle', color:'#00aaff', label:'DMSMS / Obsolescence' },
    'Safety':        { icon:'fa-shield-halved',  color:'#00aaff', label:'Safety' },
    'Testing':       { icon:'fa-vial',           color:'#00aaff', label:'Testing & Evaluation' },
    'Quality':       { icon:'fa-certificate',    color:'#00aaff', label:'Quality Assurance' },
    'Cybersecurity': { icon:'fa-lock',           color:'#00aaff', label:'Cybersecurity & Compliance' },
    'Acquisition':   { icon:'fa-file-contract',  color:'#00aaff', label:'Acquisition & Contracts' },
    'Configuration': { icon:'fa-sitemap',        color:'#00aaff', label:'Configuration Management' },
    'Technical Data':{ icon:'fa-book-open',       color:'#00aaff', label:'Technical Data & Publications' },
    'Cost Analysis': { icon:'fa-calculator',      color:'#00aaff', label:'Cost Analysis' },
    'Engineering':   { icon:'fa-gears',          color:'#8b8fa3', label:'Systems Engineering' },
    'Program Mgmt':  { icon:'fa-diagram-project', color:'#00aaff', label:'Program Management' },
    'Ordnance':      { icon:'fa-bomb',           color:'#00aaff', label:'Ordnance & Ammunition' },
    'Security':      { icon:'fa-user-shield',    color:'#00aaff', label:'Information Security' },
};

// Branch metadata
const DOC_BRANCHES = {
    'JOINT': { label:'Joint / DoD-Wide', color:'#00aaff' },
    'USN':   { label:'U.S. Navy',        color:'#003f87' },
};
